# Generated by Django 5.1 on 2024-09-02 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeu',
            name='duration',
        ),
    ]
