# Generated by Django 5.1 on 2024-09-03 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeu',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timeu',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
